POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "fugena",
    "password": "2212"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "fumine",
    "password": "2212"
}